laser_tilt_controller:
  type:  pr2_mechanism_controllers/LaserScannerTrajController
  joint: laser_tilt_mount_joint
  gains:
    p: 0.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0
  velocity_filter:
    - name: low_pass
      type: filters/TransferFunctionFilterDouble
      params:
        a: [1.0, -0.1]
        b: [0.9]
  max_velocity:    0
  max_acceleration: 0

