(cl:defpackage action_pr2-srv
  (:use )
  (:export
   "EXECUTECARTESIANTRAJECTORY"
   "<EXECUTECARTESIANTRAJECTORY-REQUEST>"
   "EXECUTECARTESIANTRAJECTORY-REQUEST"
   "<EXECUTECARTESIANTRAJECTORY-RESPONSE>"
   "EXECUTECARTESIANTRAJECTORY-RESPONSE"
  ))

